import { UserLayout } from '@/components/user/user-layout';
import { userDashboardStyles } from '@/components/user/user-dashboard';

const styles: string[] = [
  ...userDashboardStyles,
  String.raw`
.page-content.page-bookings{max-width:1100px;margin:0 auto;width:100%}
.bookings-error{margin-bottom:14px;color:#b91c1c;font-size:13px}
.bookings-metric-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px;margin-bottom:22px}
.bookings-metric-card{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:14px 18px;display:flex;align-items:center;gap:14px;min-height:92px}
.bookings-metric-card p{margin:0 0 4px;color:#6b7280;font-size:13px;line-height:1.25}.bookings-metric-card strong{font-size:28px;line-height:1;font-weight:650;color:#111;letter-spacing:-.03em}.bookings-stat-icon{width:42px;height:42px;border-radius:12px;display:grid;place-items:center;font-size:20px}.bookings-stat-icon--blue{background:#dbeafe;color:#2563eb}.bookings-stat-icon--amber{background:#fef3c7;color:#ca8a04}.bookings-stat-icon--green{background:#dcfce7;color:#16a34a}.bookings-stat-icon--red{background:#fee2e2;color:#dc2626}
.bookings-filter-bar{border-bottom:1.5px solid #e5e7eb;margin-bottom:32px}.bookings-filter-tabs{display:flex;gap:0;overflow-x:auto}.bookings-filter-tab{appearance:none;border:0;background:transparent;color:#6b7280;font-size:14px;font-weight:500;padding:13px 18px 12px;border-bottom:2px solid transparent;cursor:pointer;white-space:nowrap}.bookings-filter-tab.active{color:#111;border-bottom-color:#111}.bookings-filter-tab span{margin-left:4px;color:#9ca3af;font-size:12px}
.bookings-list-card{background:#fff;border:1px solid #e5e7eb;border-radius:12px;overflow:hidden}.bookings-table{width:100%;border-collapse:collapse}.bookings-table th{text-align:left;font-size:11px;font-weight:650;text-transform:uppercase;letter-spacing:.06em;color:#9ca3af;padding:10px 20px;border-bottom:1px solid #f3f4f6}.bookings-table td{padding:12px 20px;min-height:56px;border-bottom:1px solid #f3f4f6;vertical-align:middle}.bookings-table tbody tr{cursor:pointer}.bookings-table tbody tr:hover{background:#fafafa}.bookings-table tbody tr:last-child td{border-bottom:0}.bookings-row-client{display:flex;align-items:center;gap:10px}.bookings-client-avatar{width:30px;height:30px;border-radius:999px;background:#f5f3ff;color:#7c3aed;font-size:11px;font-weight:650;display:grid;place-items:center;flex:0 0 auto}.bookings-client-name{font-size:13px;font-weight:550;color:#111;line-height:1.25}.bookings-client-phone,.bookings-provider,.bookings-date-cell span{display:block;font-size:11px;color:#9ca3af;margin-top:2px}.bookings-service-name{font-size:13px;color:#111}.bookings-service-name em{color:#9ca3af;font-style:italic}.bookings-date-cell{font-size:13px;font-weight:500;color:#111}.booking-status{display:inline-flex;align-items:center;gap:4px;border-radius:999px;padding:3px 9px;font-size:11px;font-weight:550;white-space:nowrap}.booking-status--captured,.booking-status--completed{background:#f3f4f6;color:#6b7280}.booking-status--link{background:#eff6ff;color:#2563eb}.booking-status--confirmed{background:#f0fdf4;color:#16a34a}.booking-status--warning{background:#fefce8;color:#ca8a04}.booking-status--cancelled{background:#fef2f2;color:#dc2626}.booking-status--rescheduled{background:#fff7ed;color:#ea580c}.bookings-view-btn{border:1px solid #e5e7eb;border-radius:8px;background:#fff;color:#374151;padding:5px 12px;font-size:12px;cursor:pointer}.bookings-view-btn:hover{border-color:#7c3aed;color:#7c3aed}
.bookings-empty{text-align:center;padding:54px 20px}.bookings-empty-icon{font-size:32px;opacity:.3;margin-bottom:12px}.bookings-empty h3{margin:0 0 6px;font-size:16px;color:#111}.bookings-empty p{margin:0 auto 16px;max-width:360px;font-size:13px;color:#6b7280}.bookings-empty-btn{display:inline-flex;align-items:center;border:1px solid #111;border-radius:10px;color:#111;text-decoration:none;padding:9px 14px;font-size:13px;font-weight:550}.bookings-pagination{display:flex;justify-content:center;align-items:center;gap:14px;margin-top:18px}.bookings-pagination button{border:1px solid #e5e7eb;border-radius:8px;background:#fff;color:#374151;padding:7px 12px;font-size:12px}.bookings-pagination button:disabled{opacity:.45;cursor:not-allowed}.bookings-pagination span,.bookings-count-note{font-size:12px;color:#9ca3af}.bookings-count-note{text-align:center;margin-top:8px}
.mobile-bookings{display:none}.booking-detail-overlay{position:fixed;inset:0;background:rgba(0,0,0,.35);z-index:1000;display:flex;justify-content:flex-end}.booking-detail-panel{width:380px;max-width:100%;height:100%;background:#fff;box-shadow:-20px 0 40px rgba(15,23,42,.18);padding:22px;overflow:auto;animation:bookingSlideIn .18s ease-out}@keyframes bookingSlideIn{from{transform:translateX(18px);opacity:.8}to{transform:translateX(0);opacity:1}}.booking-detail-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;border-bottom:1px solid #f3f4f6;padding-bottom:16px;margin-bottom:18px}.booking-detail-head h2{margin:0 0 4px;font-size:18px;color:#111}.booking-detail-head p,.booking-muted,.booking-detail-loading{margin:0;color:#6b7280;font-size:13px}.booking-detail-head button{width:32px;height:32px;border:1px solid #e5e7eb;background:#fff;border-radius:999px;font-size:20px;line-height:1;cursor:pointer}.booking-detail-section{border-bottom:1px solid #f3f4f6;padding:0 0 18px;margin:0 0 18px}.booking-detail-section h3{margin:0 0 12px;font-size:13px;color:#111}.booking-detail-section dl{display:grid;grid-template-columns:110px 1fr;gap:9px 12px;margin:0}.booking-detail-section dt{font-size:12px;color:#9ca3af}.booking-detail-section dd{margin:0;font-size:13px;color:#111}.booking-detail-section a{color:#7c3aed;text-decoration:none}.booking-sms-timeline{display:grid;gap:12px}.booking-sms-entry{display:flex;gap:10px}.booking-sms-entry>span{width:9px;height:9px;background:#16a34a;border-radius:999px;margin-top:4px;flex:0 0 auto}.booking-sms-entry>span.failed{background:#dc2626}.booking-sms-entry strong{font-size:13px;color:#111}.booking-sms-entry p{margin:2px 0 0;font-size:12px;color:#9ca3af}.booking-override-actions{display:grid;gap:10px}.booking-override-actions button{height:40px;border:1px solid #e5e7eb;background:#fff;border-radius:9px;font-size:13px;font-weight:550;color:#111;cursor:pointer}.booking-override-actions button.danger{border-color:#fca5a5;color:#dc2626}
@media (max-width:900px){.bookings-metric-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.bookings-table-desktop{display:none}.mobile-bookings{display:grid}.mobile-booking-card{appearance:none;border:0;border-bottom:1px solid #f3f4f6;background:#fff;text-align:left;padding:14px 16px;display:grid;gap:10px;cursor:pointer}.mobile-booking-card:last-child{border-bottom:0}.mobile-booking-top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.mobile-booking-meta{display:flex;justify-content:space-between;gap:14px;font-size:12px;color:#6b7280}.booking-detail-overlay{align-items:flex-end}.booking-detail-panel{width:100%;height:auto;max-height:88vh;border-radius:20px 20px 0 0;animation:bookingSheetIn .18s ease-out}@keyframes bookingSheetIn{from{transform:translateY(24px);opacity:.8}to{transform:translateY(0);opacity:1}}}
@media (max-width:640px){.bookings-metric-grid{grid-template-columns:1fr}.bookings-filter-tab{padding-left:12px;padding-right:12px}.booking-detail-section dl{grid-template-columns:1fr}.booking-detail-section dt{margin-top:4px}}
`,
];

const scripts: string[] = [];

export const userBookingsStyles = styles;
export const userBookingsScripts = scripts;
export const templateTitle = 'Bookings';

export function UserBookingsTemplate() {
  return (
    <UserLayout styles={styles} scripts={scripts} scriptPrefix="user-bookings">
      <div />
    </UserLayout>
  );
}
