import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const promptsRoot = path.join(repoRoot, 'prompts');
const outputFile = path.join(repoRoot, 'src/agent/prompts/generated-prompt-packs.ts');

const verticalFiles = {
  'nail-salon': 'verticals/nail-salon.txt',
  'hair-salon': 'verticals/hair-salon.txt',
  'day-spa': 'verticals/day-spa.txt',
  'med-spa': 'verticals/med-spa.txt',
  'beauty-clinic': 'verticals/beauty-clinic.txt',
};

const callTypeFiles = {
  inbound_booking: 'call-types/inbound-booking.txt',
  reschedule: 'call-types/inbound-reschedule.txt',
  cancellation: 'call-types/inbound-cancellation.txt',
  complaint_escalation: 'call-types/inbound-complaint.txt',
  demo_outbound: 'call-types/outbound-demo-web-call.txt',
  callback: 'call-types/callback.txt',
  outbound_reminder: 'call-types/outbound-reminder.txt',
  outbound_no_show_followup: 'call-types/outbound-no-show-followup.txt',
  outbound_slot_recovery: 'call-types/outbound-slot-recovery.txt',
  outbound_reactivation: 'call-types/outbound-reactivation.txt',
};

const runtimePromptFiles = {
  realtimeConstrainedPolicy: 'runtime/realtime-constrained-policy.txt',
  realtimeNativeOpenaiConstrainedPolicy: 'runtime/realtime-native-openai-constrained-policy.txt',
  realtimeGreetingResponseInstructions: 'runtime/realtime-greeting-response-instructions.txt',
  openaiViBookingTranscription: 'runtime/openai-vi-booking-transcription.txt',
  fallbackGreetingEn: 'runtime/fallback-greeting-en.txt',
  fallbackGreetingEnWithBusiness: 'runtime/fallback-greeting-en-with-business.txt',
  fallbackGreetingVi: 'runtime/fallback-greeting-vi.txt',
  fallbackGreetingViWithBusiness: 'runtime/fallback-greeting-vi-with-business.txt',
  publicDemoFallbackCustomInstructions: 'runtime/public-demo-fallback-custom-instructions.txt',
  productionCustomInstructions: 'runtime/production-custom-instructions.txt',
};

/**
 * Extract only the ### Prompt Content section from structured prompt files.
 * Files use a standard layout:
 *   ## FILE HEADER
 *   ### Purpose          ← documentation, stripped
 *   ### What belongs here ← documentation, stripped
 *   ### What must NOT belong here ← documentation, stripped
 *   ### Prompt Content   ← behavioral instructions, KEPT
 *   ### Notes ...        ← documentation, stripped
 *
 * For files without the ### Prompt Content marker (e.g. core/*.txt, runtime/*.txt),
 * the full content is returned — those files contain only instructions with no doc sections.
 */
function stripDocSections(raw) {
  const normalized = raw.replace(/\r\n/g, '\n');
  const marker = /^### Prompt Content\s*$/m;
  const match = marker.exec(normalized);
  if (!match) return normalized.trim();
  const afterMarker = normalized.slice(match.index + match[0].length);
  // Stop at next ### section (e.g. ### Notes for maintainability)
  const nextSection = /^###\s+/m.exec(afterMarker);
  const content = nextSection ? afterMarker.slice(0, nextSection.index) : afterMarker;
  return content.trim();
}

async function readPrompt(relativePath) {
  const raw = await readFile(path.join(promptsRoot, relativePath), 'utf8');
  return stripDocSections(raw);
}

function titleFromPrompt(content, fallback) {
  return content.match(/^##\s+(.+)$/m)?.[1]?.trim() ?? fallback;
}

function toTs(value) {
  return JSON.stringify(value, null, 2);
}

function renderPromptPackRecord(record) {
  return `{
${Object.entries(record)
  .map(
    ([key, pack]) => `  ${JSON.stringify(key)}: {
    id: ${toTs(pack.id)},
    title: ${toTs(pack.title)},
    content: ${toTs(pack.content)},
  },`,
  )
  .join('\n')}
}`;
}

const corePrompt = await readPrompt('core/system.txt');
const guardrailPrompt = await readPrompt('core/guardrails.txt');
const demoGuardrailPrompt = await readPrompt('core/demo-guardrails.txt');

async function readRawTitle(relativePath, fallback) {
  const raw = await readFile(path.join(promptsRoot, relativePath), 'utf8');
  return titleFromPrompt(raw, fallback);
}

const verticalPacks = {};
for (const [vertical, relativePath] of Object.entries(verticalFiles)) {
  const [content, title] = await Promise.all([
    readPrompt(relativePath),
    readRawTitle(relativePath, vertical),
  ]);
  verticalPacks[vertical] = { id: `vertical:${vertical}`, title, content };
}

const callTypePacks = {};
for (const [callType, relativePath] of Object.entries(callTypeFiles)) {
  const [content, title] = await Promise.all([
    readPrompt(relativePath),
    readRawTitle(relativePath, callType),
  ]);
  callTypePacks[callType] = { id: `call-type:${callType}`, title, content };
}

const runtimePrompts = {};
for (const [key, relativePath] of Object.entries(runtimePromptFiles)) {
  runtimePrompts[key] = await readPrompt(relativePath);
}

const generated = `// This file is generated by scripts/sync-prompts.mjs.
// Edit files in /prompts, then run npm run prompts:sync.

import type { PromptPack, VoicePromptCallType, VoicePromptVertical } from './types';

export const CORE_VOICE_PROMPT = ${toTs(corePrompt)};

export const UNIVERSAL_GUARDRAIL_PROMPT = ${toTs(guardrailPrompt)};

export const DEMO_GUARDRAIL_PROMPT = ${toTs(demoGuardrailPrompt)};

export const VERTICAL_PROMPT_PACKS = ${renderPromptPackRecord(verticalPacks)} satisfies Record<VoicePromptVertical, PromptPack>;

export const CALL_TYPE_PROMPT_PACKS = ${renderPromptPackRecord(callTypePacks)} satisfies Record<VoicePromptCallType, PromptPack>;

export const RUNTIME_PROMPT_TEMPLATES = ${toTs(runtimePrompts)} as const;
`;

await mkdir(path.dirname(outputFile), { recursive: true });
const nextContent = `${generated}\n`;
let previous = '';
try {
  previous = await readFile(outputFile, 'utf8');
} catch {
  // missing output — write below
}
if (previous === nextContent) {
  console.log(
    `Prompt packs unchanged; skipped writing ${path.relative(repoRoot, outputFile)} (avoids dirty git after npm run build).`,
  );
} else {
  await writeFile(outputFile, nextContent, 'utf8');
  console.log(`Synced prompt packs to ${path.relative(repoRoot, outputFile)}`);
}
